[project]
name = "expensemate"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.8",
    "google-genai>=1.52.0",
    "google-generativeai>=0.8.5",
    "pillow>=12.0.0",
    "python-dotenv>=1.2.1",
    "reportlab>=4.4.5",
]
